name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  info-Action:
    runs-on: ubuntu-latest
    steps:
      - run: echo "the job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "this job is now running on a ${{runner.os}} server hosted by Github"
      - run: echo "The name of your branch is ${{github.ref}}  and your repository is ${{github.repository}}"

      - name: check out repository code
        uses: actions/checkout@v4

      - run: echo " this ${{github.repository}} repository has been cloned to the runner"
      - run: |
          ls ${{ github.workspace }}
      - run: echo "This job's status is ${{ job.status }}.";
      
